login/urls.py
from django.conf.urls import url
from login import views
from django.urls import path

app_name = 'login'

urlpatterns = [
    path('register/',views.register,name='register'),
    path('user_login/',views.user_login,name = "user_login"),
    path('',views.index,name='index'),
    path('otp/',views.otp,name='otp'),
    path('logout/',views.user_logout,name="logout"),
    path('special/',views.special,name="special"),
]

sportsEquipment/urls.py
from django.conf.urls import url
from sportsEquipment import views,apiviews
from django.urls import path,include
from rest_framework import routers

# router = routers.DefaultRouter()
# router.register(r'eqpmnts', apiviews.EquipmentsViewSet)
# router.register(r'eqpmntsList', apiviews.EquipmentRequestViewSet)

app_name = 'sportsEquipment'
# urlpatterns = [
#     path('', include(router.urls)),
#     # path('api-auth/', include('rest_framework.urls', namespace='rest_framework'))
# ]
urlpatterns = [
    # Return view response
    path('',views.home,name='home'),
    path('home/',views.home,name='home'),
    path(r'eqpRequest/',views.eqpRequest,name='eqpRequest'),
    path(r'pendingRequest/',views.pendingRequest,name='pendingRequest'),
    path(r'approvedRequest/',views.approvedRequest,name='approvedRequest'),
    path(r'checkAvailability/',views.checkAvailability,name='checkAvailability'),
    path(r'processRequest/',views.processRequest,name='processRequest'),
    path(r'processReturnRequest/',views.processReturnRequest,name='processReturnRequest'),
    path(r'viewRequest/',views.viewRequest,name='viewRequest'),
    path(r'addEquip/',views.addEquip,name='addEquip'),
    path(r'viewEquipList/',views.viewInventory,name='viewEquipList'),
    path(r'editEquipList/(?P<pk>\d+)',views.editEquipList,name='editEquipList'),
    path(r'deleteEqp/(?P<pk>\d+)',views.deleteEqp,name='deleteEqp'),
    path(r'penalty/',views.penalty,name='penalty'),
    # View response

    # Return API response
    path(r'getAllEqps/',apiviews.getAllEqps,name='getAllEqps'),
    path(r'getAllEqpReqs/',apiviews.getAllEqpReqs,name='getAllEqpReqs'),
    path(r'checkAvailability/<reqId>',apiviews.checkAvailability,name='checkAvailability'),
    # API response

    #for ground
    path(r'addGround/',views.addGround,name='addGround'),
    path(r'groundRequests/',views.groundRequests,name='groundRequests'),

    path(r'viewGrounds/',views.viewGrounds,name='viewGrounds'),

]

sportsroom/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views as auth_views
from login import views
from django.conf.urls import url, include
from django.contrib import admin

from django.conf import settings
from django.conf.urls.static import static

admin.site.site_title = "SportsRoom Site Admin"
admin.site.site_header = "SportsRoom Site Admin"
admin.site.index_title ="SportsRoom Site Admin"


urlpatterns = [
    path('',views.index,name='index'),
    path('admin/', admin.site.urls),
    path('login/',include('login.urls')),
    path('sportsEquipment/',include('sportsEquipment.urls')),
    path('logout/',views.user_logout,name="logout"),
    # path('special/',views.special,name="special"),

    # path('password-reset/',auth_views.password_reset,name="password_reset"),
    # path("password-reset/done/",auth_views.password_reset_done,name="password_reset_done"),
    # path('password-reset/confirm/(?P<uidb64>[\w-]+)/(?P<token>[\w-]+)/',auth_views.password_reset_confirm,name="password_reset_confirm"),
    # path("password-reset/complete/",auth_views.password_reset_complete,name="password_reset_complete"),

    path('',include('django.contrib.auth.urls')),
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

templates/AdminUser/addEquip.html
{% extends 'MasterLayout/baseLayout.html' %}



{% block rightbar %}

              <div class ="profImg">     
                    <img  src="/media/{{ userProfile.profile_pic }}" style="width:50px" alt="{{ user }}"/>
                    {% if user.is_authenticated %}
                    </div> 
                    <div class="dropdown">
                    <!-- <a class="nav-link" href="{% url 'login:logout' %}">Logout</a>
                      {% else %}
                    <a class="nav-link" href="{% url 'login:user_login' %}">Login</a>
                      {% endif %}
   -->
                    
                    <button class="btn dropdown-toggle" type="button" data-toggle="dropdown" style="color: white"></button>
                    <!-- <span class="caret"></span></button> -->
                    <ul class="dropdown-menu">
                    {% if user.is_authenticated %}
                      <li><a class="nav-link" href="{% url 'login:logout' %}">Logout</a></li>
                      <li><a class="nav-link" href="#">Hello, {{ user.username }}</a></li>
                    {% else %}
                      <li><a class="nav-link" href="{% url 'login:user_login' %}">Login</a></li>
                      <li><a class="nav-link" href="#">Hello, {{ user.username }}</a></li>
                    {% endif %}
                    </ul>
</div>
            {%  endblock%}

{% block body %}

  <div class="container" style="font-size: 14px">
  	<br>
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <input type="submit" value="Submit">
  </form>
  </div>

{% endblock %}

templates/AdminUser/addGround.html
{% extends 'MasterLayout/baseLayout.html' %}


{% block rightbar %}

              <div class ="profImg">     
                    <img  src="/media/{{ userProfile.profile_pic }}" style="width:50px" alt="{{ user }}"/>
                    {% if user.is_authenticated %}
                    </div> 
                    <div class="dropdown">
                    <!-- <a class="nav-link" href="{% url 'login:logout' %}">Logout</a>
                      {% else %}
                    <a class="nav-link" href="{% url 'login:user_login' %}">Login</a>
                      {% endif %}
   -->
                    
                    <button class="btn dropdown-toggle" type="button" data-toggle="dropdown" style="color: white"></button>
                    <!-- <span class="caret"></span></button> -->
                    <ul class="dropdown-menu">
                    {% if user.is_authenticated %}
                      <li><a class="nav-link" href="{% url 'login:logout' %}">Logout</a></li>
                      <li><a class="nav-link" href="#">Hello, {{ user.username }}</a></li>
                    {% else %}
                      <li><a class="nav-link" href="{% url 'login:user_login' %}">Login</a></li>
                      <li><a class="nav-link" href="#">Hello, {{ user.username }}</a></li>
                    {% endif %}
                    </ul>
</div>
            {%  endblock%}

{% block body %}

  <div class="container" style="font-size: 14px">
  	<br>
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <input type="submit" value="Submit">
  </form>
  </div>

{% endblock %}

templates/AdminUser/deleteEquip.html
{% extends 'MasterLayout/baseLayout.html' %}

{% block rightbar %}

              <div class ="profImg">     
                    <img  src="/media/{{ userProfile.profile_pic }}" style="width:50px" alt="{{ user }}"/>
                    {% if user.is_authenticated %}
                    </div> 
                    <div class="dropdown">
                    <!-- <a class="nav-link" href="{% url 'login:logout' %}">Logout</a>
                      {% else %}
                    <a class="nav-link" href="{% url 'login:user_login' %}">Login</a>
                      {% endif %}
   -->
                    
                    <button class="btn dropdown-toggle" type="button" data-toggle="dropdown" style="color: white"></button>
                    <!-- <span class="caret"></span></button> -->
                    <ul class="dropdown-menu">
                    {% if user.is_authenticated %}
                      <li><a class="nav-link" href="{% url 'login:logout' %}">Logout</a></li>
                      <li><a class="nav-link" href="#">Hello, {{ user.username }}</a></li>
                    {% else %}
                      <li><a class="nav-link" href="{% url 'login:user_login' %}">Login</a></li>
                      <li><a class="nav-link" href="#">Hello, {{ user.username }}</a></li>
                    {% endif %}
                    </ul>
</div>
            {%  endblock%}

{% block body %}

  <div class="container">
    <form action='.' method="POST">{% csrf_token %}
    	<h3> Item Deleted!!<h3>
    	<div>
    		
            <a href="{% url 'sportsEquipment:viewEquipList' %}" class="btn btn-primary btn-sm" role="button" aria-pressed="true" > OK</a>

    	</div>
      
  </form>
  </div>

{% endblock %}



<!-- <input onClick="delete(this.id)" id={{ object.eqpId }} role="button" value='Yes'/> 
<input   id='btnDelete'></input>
<a href= '../..'>Cancel</a> -->

templates/AdminUser/editEquipList.html
{% extends 'MasterLayout/baseLayout.html' %}

{% block rightbar %}

              <div class ="profImg">     
                    <img  src="/media/{{ userProfile.profile_pic }}" style="width:50px" alt="{{ user }}"/>
                    {% if user.is_authenticated %}
                    </div> 
                    <div class="dropdown">
                    <!-- <a class="nav-link" href="{% url 'login:logout' %}">Logout</a>
                      {% else %}
                    <a class="nav-link" href="{% url 'login:user_login' %}">Login</a>
                      {% endif %}
   -->
                    
                    <button class="btn dropdown-toggle" type="button" data-toggle="dropdown" style="color: white"></button>
                    <!-- <span class="caret"></span></button> -->
                    <ul class="dropdown-menu">
                    {% if user.is_authenticated %}
                      <li><a class="nav-link" href="{% url 'login:logout' %}">Logout</a></li>
                      <li><a class="nav-link" href="#">Hello, {{ user.username }}</a></li>
                    {% else %}
                      <li><a class="nav-link" href="{% url 'login:user_login' %}">Login</a></li>
                      <li><a class="nav-link" href="#">Hello, {{ user.username }}</a></li>
                    {% endif %}
                    </ul>
</div>
            {%  endblock%}

{% block body %}

  <div class="container">
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <input type="submit" value="Submit">
  </form>
  </div>

{% endblock %}

templates/AdminUser/pendingRequest.html
{% extends 'MasterLayout/baseLayout.html' %}

{% block rightbar %}

              <div class ="profImg">
                    <img  src="/media/{{ userProfile.profile_pic }}" style="width:50px" alt="{{ user }}"/>
                    {% if user.is_authenticated %}
                    </div>
                    <div class="dropdown">
                    <!-- <a class="nav-link" href="{% url 'login:logout' %}">Logout</a>
                      {% else %}
                    <a class="nav-link" href="{% url 'login:user_login' %}">Login</a>
                      {% endif %}
   -->

                    <button class="btn dropdown-toggle" type="button" data-toggle="dropdown" style="color: white"></button>
                    <!-- <span class="caret"></span></button> -->
                    <ul class="dropdown-menu">
                    {% if user.is_authenticated %}
                      <li><a class="nav-link" href="{% url 'login:logout' %}">Logout</a></li>
                      <li><a class="nav-link" href="#">Hello, {{ user.username }}</a></li>
                    {% else %}
                      <li><a class="nav-link" href="{% url 'login:user_login' %}">Login</a></li>
                      <li><a class="nav-link" href="#">Hello, {{ user.username }}</a></li>
                    {% endif %}
                    </ul>
</div>
            {%  endblock%}

{% block body %}

  <div class="container" style="font-size: 14px">
    <br>

    <table class="table table-hover">
    <thead>
      <tr>
        <th>Request No</th>
        <th>Equipment</th>
        <th>Quantity</th>
        <th>Username</th>
        <th>Date of Request</th>

        <th></th>
      </tr>
    </thead>

    <tbody>

      {% for pendingRequest in lstPendingRequest %}

      <tr>
        <td>{{ pendingRequest.reqId }}
        <td>{{ pendingRequest.eqp.eqpName }}</td>
        <td>{{ pendingRequest.quantity }} </td>
        <td>{{ pendingRequest.user.username }}</td>
        <td>{{ pendingRequest.dtOfRequest.date }}</td>
        <td>
          <!-- {% if availability %}
            <div>availability</div>
          {% else %} -->
          <form>
            {% csrf_token %}
             <a onClick="checkAvailability(this.id)" id={{ pendingRequest.reqId }} role="button" aria-pressed="true"><input value="Check Availability" class="btn btn-primary" id={{ pendingRequest.reqId }} readonly style="font-size: 14px"></input></a>
          </form>
          <!-- {% endif %} -->
        </td>
        <td>
            <a href="{% url 'sportsEquipment:processRequest' %}?reqId={{ pendingRequest.reqId }}&isAcceptRequest=1" class="btn btn-success btn-sm" role="button" aria-pressed="true" style="font-size: 14px"> Approve</a>
            <a href="{% url 'sportsEquipment:processRequest' %}?reqId={{ pendingRequest.reqId }}&isAcceptRequest=0" class="btn btn-danger btn-sm" role="button" aria-pressed="true" style="font-size: 14px"> Reject</a>
        </td>


      </tr>

      {% endfor %}
    </tbody>
  </table>


  </div>

{% endblock %}

templates/AdminUser/processedRequest.html
{% extends 'MasterLayout/baseLayout.html' %}

{% block rightbar %}

              <div class ="profImg">     
                    <img  src="/media/{{ userProfile.profile_pic }}" style="width:50px" alt="{{ user }}"/>
                    {% if user.is_authenticated %}
                    </div> 
                    <div class="dropdown">
                    <!-- <a class="nav-link" href="{% url 'login:logout' %}">Logout</a>
                      {% else %}
                    <a class="nav-link" href="{% url 'login:user_login' %}">Login</a>
                      {% endif %}
   -->
                    
                    <button class="btn dropdown-toggle" type="button" data-toggle="dropdown" style="color: white"></button>
                    <!-- <span class="caret"></span></button> -->
                    <ul class="dropdown-menu">
                    {% if user.is_authenticated %}
                      <li><a class="nav-link" href="{% url 'login:logout' %}">Logout</a></li>
                      <li><a class="nav-link" href="#">Hello, {{ user.username }}</a></li>
                    {% else %}
                      <li><a class="nav-link" href="{% url 'login:user_login' %}">Login</a></li>
                      <li><a class="nav-link" href="#">Hello, {{ user.username }}</a></li>
                    {% endif %}
                    </ul>
</div>
            {%  endblock%}

{% block body %}
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script>
    $(document).ready(function(){
      $("#myInput").on("keyup", function() {
        var value = $(this).val().toLowerCase();
        $("#myTable tr").filter(function() {
          $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
        });
      });
    });
    </script>


  <div class="container" style="font-size: 14px">
    <br>
    <h2>Search Request</h2>
    <p>Type key words in the input field to search the List</p>  
    <input id="myInput" type="text" placeholder="Search..">
    <br><br>

    <table class="table table-hover">
    <thead>
      <tr>
        <th>Request No</th>
        <th>Equipment</th>
        <th>Quantity</th>
        <th>Username</th>
        <th>Date of Request</th>
        <th>Date of Approval</th>
        <th>Expected Return Date</th>
        <th></th>
      </tr>
    </thead>

    <tbody id="myTable">

      {% for processedRequest in lstProcessedRequest %}

      <tr>
        <td>{{ processedRequest.reqId }}
        <td>{{ processedRequest.eqp.eqpName }}</td>
        <td>{{ processedRequest.quantity }} </td>
        <td>{{ processedRequest.user.username }}</td>
        <td>{{ processedRequest.dtOfRequest.date }}</td>
        <td>{{ processedRequest.dtAvailed.date }}</td>
        <td>{{ processedRequest.dtOfExpRet.date }}</td>

        <td>
            {% if processedRequest.reqStatus == 1 %}
                <a href="#" class="btn btn-success btn-sm" role="button" aria-pressed="true" style="font-size: 14px"> Approved </a>
                <a href="{% url 'sportsEquipment:processReturnRequest' %}?reqId={{ processedRequest.reqId }}" class="btn btn-primary btn-sm" role="button" aria-pressed="true" style="font-size: 14px"> Return</a>

            {% elif processedRequest.reqStatus == 2%}
                <a href="#" class="btn btn-danger btn-sm" role="button" aria-pressed="true" style="font-size: 14px"> Rejected </a>

            {% else %}
                <a href="#" class="btn btn-secondary btn-sm" role="button" aria-pressed="true" style="font-size: 14px"> Returned </a>
            {% endif %}
        </td>


      </tr>

      {% endfor %}
    </tbody>
  </table>


  </div>

{% endblock %}

templates/AdminUser/viewEquipList.html
{% extends 'MasterLayout/baseLayout.html' %}

{% block rightbar %}

              <div class ="profImg">     
                    <img  src="/media/{{ userProfile.profile_pic }}" style="width:50px" alt="{{ user }}"/>
                    {% if user.is_authenticated %}
                    </div> 
                    <div class="dropdown">
                    <!-- <a class="nav-link" href="{% url 'login:logout' %}">Logout</a>
                      {% else %}
                    <a class="nav-link" href="{% url 'login:user_login' %}">Login</a>
                      {% endif %}
   -->
                    
                    <button class="btn dropdown-toggle" type="button" data-toggle="dropdown" style="color: white"></button>
                    <!-- <span class="caret"></span></button> -->
                    <ul class="dropdown-menu">
                    {% if user.is_authenticated %}
                      <li><a class="nav-link" href="{% url 'login:logout' %}">Logout</a></li>
                      <li><a class="nav-link" href="#">Hello, {{ user.username }}</a></li>
                    {% else %}
                      <li><a class="nav-link" href="{% url 'login:user_login' %}">Login</a></li>
                      <li><a class="nav-link" href="#">Hello, {{ user.username }}</a></li>
                    {% endif %}
                    </ul>
</div>
            {%  endblock%}

{% block body %}
    
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script>
    $(document).ready(function(){
      $("#myInput").on("keyup", function() {
        var value = $(this).val().toLowerCase();
        $("#myTable tr").filter(function() {
          $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
        });
      });
    });
    </script>






  <div class="container" style="font-size: 14px">
    <br>


    <h2>Search Equipment</h2>
    <p>Type EqpName in the input field to search the List</p>  
    <input id="myInput" type="text" placeholder="Search..">
    <br><br>


    <table class="table table-hover">
    <thead>
      <tr>
        <!-- <th>EqpID</th> -->
        <th>EqpName</th>
        <th>Total EqpQuantity</th>
        <th>EqpAvailable</th>
        <th>Edit</th>
        <th>Delete</th>
        <!--<th>Username</th>
        <th>Date of Request</th>
        <th>Date of Approval</th>
        <th>Expected Return Date</th>
        <th>Actual Return Date</th>
        <th>Penalty Levied</th>
        <th></th>-->
      </tr>
    </thead>

    <tbody id="myTable">

      {% for request in context %}

      <tr>
        <!-- <td>{{ request.eqpId }}</td> -->
        <td>{{ request.eqpName }}</td>
        <td>{{ request.eqpQuantity }} </td>
        <td>{{ request.eqpQuantityTaken }}</td>
        <td><a href="{% url 'sportsEquipment:editEquipList' request.eqpId %}" class="btn btn-info btn-sm" role="button" style="font-size: 14px">Edit</a></td>
        <td><a href="{% url 'sportsEquipment:deleteEqp' request.eqpId %}" class="btn btn-danger btn-sm" role="button" style="font-size: 14px">Delete</a></td>
        <!--<td>{{ request.user.username }}</td>
        <td>{{ request.dtOfRequest.date }}</td>
        <td>
            {% if request.dtAvailed.date == None %}
                NA
            {% else %}
                {{ request.dtAvailed.date }}
            {% endif %}
        </td>
        <td>
            {% if request.dtAvailed.date == None %}
                NA
            {% else %}
                {{ request.dtOfExpRet.date }}
            {% endif %}
        </td>
        <td>{% if request.dtAvailed.date == None %}
                NA
            {% else %}
                {{ request.dtOfActualRet.date }}
            {% endif %}
        </td>
        <td>{% if request.dtAvailed.date == None %}
                NA
            {% else %}
                {{ request.penalty }}
            {% endif %}
        </td>

        <td>
            {% if request.reqStatus == 0 %}
                <a href="#" class="btn btn-warning btn-sm" role="button" aria-pressed="true" > Pending </a>

            {% elif request.reqStatus == 1 %}
                <a href="#" class="btn btn-success btn-sm" role="button" aria-pressed="true" > Approved </a>

            {% elif request.reqStatus == 2 %}
                <a href="#" class="btn btn-danger btn-sm" role="button" aria-pressed="true" > Rejected </a>

            {% else %}
                <a href="#" class="btn btn-primary btn-sm" role="button" aria-pressed="true" > Item Returned </a>

            {% endif %}
        </td>-->


      </tr>

      {% endfor %}

    </tbody>
  </table>


  </div>

{% endblock %}

templates/AdminUser/viewPenalty.html
{% extends 'MasterLayout/baseLayout.html' %}
<%from django.conf.settings import MEDIA_URL%>

{% block rightbar %}

              <div class ="profImg">     
                    <img  src="/media/{{ userProfile.profile_pic }}" style="width:50px" alt="{{ user }}"/>
                    {% if user.is_authenticated %}
                    </div> 
                    <div class="dropdown">
                    <!-- <a class="nav-link" href="{% url 'login:logout' %}">Logout</a>
                      {% else %}
                    <a class="nav-link" href="{% url 'login:user_login' %}">Login</a>
                      {% endif %}
   -->
                    
                    <button class="btn dropdown-toggle" type="button" data-toggle="dropdown" style="color: white"></button>
                    <!-- <span class="caret"></span></button> -->
                    <ul class="dropdown-menu">
                    {% if user.is_authenticated %}
                      <li><a class="nav-link" href="{% url 'login:logout' %}">Logout</a></li>
                      <li><a class="nav-link" href="#">Hello, {{ user.username }}</a></li>
                    {% else %}
                      <li><a class="nav-link" href="{% url 'login:user_login' %}">Login</a></li>
                      <li><a class="nav-link" href="#">Hello, {{ user.username }}</a></li>
                    {% endif %}
                    </ul>
</div>
            {%  endblock%}
            
{% block body %}
    
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script>
    $(document).ready(function(){
      $("#myInput").on("keyup", function() {
        var value = $(this).val().toLowerCase();
        $("#myTable tr").filter(function() {
          $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
        });
      });
    });
    </script>






  <div class="container" style="font-size: 14px">
    <br>


    <h2>Check Penalty</h2>
    <p>Type UserName in the input field to search the List</p>  
    <input id="myInput" type="text" placeholder="Search..">
    <br><br>


    <table class="table table-hover">
    <thead>
      <tr>
        <th>User</th>
        <th>TotalPenalty</th>
        <th>ProfilePic</th>
    
        
      </tr>
    </thead>

    <tbody id="myTable">

      {% for request in context %}

      <tr>
        <td>{{ request.user }}</td>
        <td>{{ request.totalPenalty }}</td>

        <td><img src="/media/{{ request.profile_pic }}" style="max-height:50px;border-radius: 20%" alt="{{request.user}}"/></td>

               


      </tr>

      {% endfor %}

    </tbody>
  </table>


  </div>

{% endblock %}