login/urls.py
from django.conf.urls import url
from login import views
from django.urls import path

app_name = 'login'

urlpatterns = [
    path('register/',views.register,name='register'),
    path('user_login/',views.user_login,name = "user_login"),
    path('',views.index,name='index'),
    path('otp/',views.otp,name='otp'),
    path('logout/',views.user_logout,name="logout"),
    path('special/',views.special,name="special"),
]

sportsroom/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views as auth_views
from login import views
from django.conf.urls import url, include
from django.contrib import admin

from django.conf import settings
from django.conf.urls.static import static

admin.site.site_title = "SportsRoom Site Admin"
admin.site.site_header = "SportsRoom Site Admin"
admin.site.index_title ="SportsRoom Site Admin"


urlpatterns = [
    path('',views.index,name='index'),
    path('admin/', admin.site.urls),
    path('login/',include('login.urls')),
    path('sportsEquipment/',include('sportsEquipment.urls')),
    path('logout/',views.user_logout,name="logout"),
    # path('special/',views.special,name="special"),

    # path('password-reset/',auth_views.password_reset,name="password_reset"),
    # path("password-reset/done/",auth_views.password_reset_done,name="password_reset_done"),
    # path('password-reset/confirm/(?P<uidb64>[\w-]+)/(?P<token>[\w-]+)/',auth_views.password_reset_confirm,name="password_reset_confirm"),
    # path("password-reset/complete/",auth_views.password_reset_complete,name="password_reset_complete"),

    path('',include('django.contrib.auth.urls')),
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

login/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class UserProfileInfo(models.Model):
    user        =   models.OneToOneField(User,on_delete = models.CASCADE)
    totalPenalty=   models.IntegerField(default=0)
    otp_no = 0
    profile_pic =   models.ImageField(upload_to="profile_pics",blank=True)
    is_verified = models.IntegerField(default=0)
    def __str__(self):
        return self.user.username

login/forms.py
from django import forms
from django.contrib.auth.models import User
from login.models import UserProfileInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget = forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username','email','password',)

class UserProfileInfoForm(forms.ModelForm):

    class Meta():
        model = UserProfileInfo
        fields = ('profile_pic',)

login/views.py
from django.shortcuts import render, redirect
from login.forms import UserForm,UserProfileInfoForm
from login.models import UserProfileInfo
from django import forms
from django.contrib.auth import authenticate,login,logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.core.mail import EmailMessage
import random
from django.contrib.auth.models import User

# Create your views here.
def index(request):
    if(request.user.is_authenticated):
        return redirect('/sportsEquipment/')
    return render(request,'Login/index.html')

@login_required
def special(request):
    return HttpResponse("You are logged in")

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

def validate(email):
    return email.split('@')[1] == "iiitb.org"


def otp(request):
    if request.method =='POST':
        otp_entered = request.POST.get('otp')
        otp_no = request.POST.get('otp_no')
        email = request.POST.get('email')
        user_profile = UserProfileInfo.objects.get(user=User.objects.get(email=email))
        print(type(otp_entered))
        print(type(otp_no))
        if(otp_no==otp_entered):
            user_profile.is_verified = 1
            user_profile.save()
            return render(request,'Login/login.html')
        else:
            error = "OTP doesn't match"
            #return HttpResponse(error)
            return render(request,'Login/login.html',{'error':error,})




def register(request):
    error = ""
    registered = False
    if request.method == "POST":
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            if  validate(user_form.cleaned_data.get("email")):

                otp_no = random.randint(1000000, 9999999)
                mail = EmailMessage('Sports Room Authentication', 'Authentication key: '+str(otp_no),
                    to=[user_form.cleaned_data.get("email")])
                mail.send()

                user = user_form.save()
                user.username = user.username.upper()
                user.set_password(user.password)
                user.save()

                profile = profile_form.save(commit=False)
                profile.user = user
                profile.otp_no = otp_no
                if 'profile_pic' in request.FILES:
                    profile.profile_pic = request.FILES['profile_pic']

                profile.save()

                registered = True
                return render(request,'Login/otp.html',{'otp_no':otp_no,
                    'email':user_form.cleaned_data.get("email")})
            else:
                error = "IIITB email required"
        else:
            print(user_form.errors,profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()
    return render(request,'Login/register.html',{
            'user_form':user_form,
            'profile_form':profile_form,
            'registered':registered,
            'error' : error
    })


def user_login(request):
    if request.method =='POST':

        username = request.POST.get('username').upper()
        password = request.POST.get('password')

        user = authenticate(username=username,password=password)

        if user:
            if user.is_active:
                login(request,user)
                # return HttpResponseRedirect(reverse('home'))
                userprofile = UserProfileInfo.objects.get(user=user)
                if(userprofile.is_verified==0):
                    return render(request,'Login/otp.html',{'otp_no':userprofile.otp_no,
                            'email':user.email})
                return redirect('/sportsEquipment/home')
            else:
                #return HttpResponse("ACCOUNT NOT ACTIVE")
                return render(request,'Login/login.html',{'error':"ACCOUNT NOT ACTIVE"})
        else:
            print("login Failed due to inactive account")
            return render(request,'Login/login.html',{'error':"Invalid login Details"})
        # print (userprofile.profile_pic)


    else:
        return render(request,'Login/login.html')

templates/Login/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    {% load static %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static '/css/style.css'%}">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
  </head>
  <body>
    <nav class="navbar navbar-expand navbar-dark bg-dark">
      <img src="/media/profile_pics/IIIT-B_logo copy.jpg" style="max-height:50px;border-radius: 50%;"/>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            
          <li class="nav-item active"><a class="nav-link" href="/" style="font-size:16px">SportsRoom<br>IIITB<span class="sr-only">(current)</span></a></li>
          <!-- <li class="nav-item"><a class="nav-link" href="{% url 'admin:index' %}">Admin</a></li> -->
          <li class="nav-item active"><a class="nav-link" href="{% url 'login:register' %}" style="font-size:16px">Register</a></li>

          {% if user.is_authenticated %}
            <li class="nav-item active"><a class="nav-link" href="{% url 'login:logout' %}" style="font-size:16px">Logout</a></li>
          {% else %}
          <li class="nav-item active"><a class="nav-link" href="{% url 'login:user_login' %}" style="font-size:16px">Login</a></li>
          {% endif %}
          
        </ul>
      </div>
      {% if user.is_authenticated %}
        <div class="collapse navbar-collapse">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item ">Hello, {{ user.username }}</li>
            <li><img src="{{ user.profile_pic }}" alt="img"></li>
          </ul>
        </div>
      {% endif %}
    </nav>
    <div class="container">
      {% block content %}
      {% endblock %}
    </div>
  </body>
</html>

templates/Login/index.html
{% extends "Login/base.html" %}
{% block content %}
<div class="jumbotron">
  <h1 style="text-align: center;">Welcome to SportsRoom</h1>
</div>
<div >
  <h2></h2>  
  <div id="myCarousel" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
      <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
      <li data-target="#myCarousel" data-slide-to="1"></li>
      <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner">
      <!-- <div class="item active">
        <img src="/media/images/1.jpg" alt="Los Angeles" style="width:100%;height:450px">
      </div> -->

      <div class="item active">
        <img src="/media/images/2.png" alt="Chicago" style="width:100%;height:450px">
      </div>
    
      <div class="item">
        <img src="/media/images/3.jpg" alt="New york" style="width:100%;height:450px">
      </div>
       <div class="item">
        <img src="/media/images/4.jpeg" alt="New york" style="width:100%;height:450px">
      </div>
    </div>

    <!-- Left and right controls -->
    <a class="left carousel-control" href="#myCarousel" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
</div>
{% endblock %}

templates/Login/login.html
{% extends "Login/base.html" %}
{% block content %}

{% block error_block %}
	<h4 style="color:red">{{ error }}</h4>
{% endblock %}

<div class="jumbotron">
	<h1>Please Login</h1>
	<form action="{% url 'login:user_login' %}" method="POST">
		{% csrf_token %}


		<label for="username">Username:</label>
		<input type="text" name="username" placeholder="Enter username">

		<label form="password">Password:</label>
		<input type="password" name="password" placeholder="Enter password">

		<input type="submit" name="" value="Login">
		<small>
			<a href="{% url 'password_reset' %}">Forgotten Password ?</a>
		</small>
	</form>
</div>

{% endblock %}

templates/Login/otp.html
{% extends "Login/base.html" %}
{% block content %}

<div class="jumbotron">
	<h1></h1>
	<form action="{% url 'login:otp' %}" method="POST">
		{% csrf_token %}
		<label for="otp">Enter Authentication Key sent to your email: </label>
		<input type="password" name="otp" placeholder="Enter otp">
		<input type="hidden" name="otp_no" value= {{otp_no}}>
		<input type="hidden" name="email" value= {{email}}>
		<input type="submit" name="" value="submit">
	</form>
	
	
</div>

{% endblock %}

templates/Login/register.html
{% extends "Login/base.html" %}
{% load static %}
{% block content %}
<div class="jumbotron">
  {% if registered %}
    <h1>Thank You for Registering</h1>
  {% else %}
  <p style="color:red">{{ error }}</p>
    <h1>Register Here!!</h1>
    <form class="" method="post" enctype="multipart/form-data">
      {% csrf_token %}
      {{ user_form.as_p }}
      {{ profile_form.as_p }}
      <input type="submit" name="" value="Register">

    </form>
  {% endif %}

</div>
{% endblock %}