login/urls.py
from django.conf.urls import url
from login import views
from django.urls import path

app_name = 'login'

urlpatterns = [
    path('register/',views.register,name='register'),
    path('user_login/',views.user_login,name = "user_login"),
    path('',views.index,name='index'),
    path('otp/',views.otp,name='otp'),
    path('logout/',views.user_logout,name="logout"),
    path('special/',views.special,name="special"),
]

sportsEquipment/urls.py
from django.conf.urls import url
from sportsEquipment import views,apiviews
from django.urls import path,include
from rest_framework import routers

# router = routers.DefaultRouter()
# router.register(r'eqpmnts', apiviews.EquipmentsViewSet)
# router.register(r'eqpmntsList', apiviews.EquipmentRequestViewSet)

app_name = 'sportsEquipment'
# urlpatterns = [
#     path('', include(router.urls)),
#     # path('api-auth/', include('rest_framework.urls', namespace='rest_framework'))
# ]
urlpatterns = [
    # Return view response
    path('',views.home,name='home'),
    path('home/',views.home,name='home'),
    path(r'eqpRequest/',views.eqpRequest,name='eqpRequest'),
    path(r'pendingRequest/',views.pendingRequest,name='pendingRequest'),
    path(r'approvedRequest/',views.approvedRequest,name='approvedRequest'),
    path(r'checkAvailability/',views.checkAvailability,name='checkAvailability'),
    path(r'processRequest/',views.processRequest,name='processRequest'),
    path(r'processReturnRequest/',views.processReturnRequest,name='processReturnRequest'),
    path(r'viewRequest/',views.viewRequest,name='viewRequest'),
    path(r'addEquip/',views.addEquip,name='addEquip'),
    path(r'viewEquipList/',views.viewInventory,name='viewEquipList'),
    path(r'editEquipList/(?P<pk>\d+)',views.editEquipList,name='editEquipList'),
    path(r'deleteEqp/(?P<pk>\d+)',views.deleteEqp,name='deleteEqp'),
    path(r'penalty/',views.penalty,name='penalty'),
    # View response

    # Return API response
    path(r'getAllEqps/',apiviews.getAllEqps,name='getAllEqps'),
    path(r'getAllEqpReqs/',apiviews.getAllEqpReqs,name='getAllEqpReqs'),
    path(r'checkAvailability/<reqId>',apiviews.checkAvailability,name='checkAvailability'),
    # API response

    #for ground
    path(r'addGround/',views.addGround,name='addGround'),
    path(r'groundRequests/',views.groundRequests,name='groundRequests'),

    path(r'viewGrounds/',views.viewGrounds,name='viewGrounds'),

]

sportsroom/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views as auth_views
from login import views
from django.conf.urls import url, include
from django.contrib import admin

from django.conf import settings
from django.conf.urls.static import static

admin.site.site_title = "SportsRoom Site Admin"
admin.site.site_header = "SportsRoom Site Admin"
admin.site.index_title ="SportsRoom Site Admin"


urlpatterns = [
    path('',views.index,name='index'),
    path('admin/', admin.site.urls),
    path('login/',include('login.urls')),
    path('sportsEquipment/',include('sportsEquipment.urls')),
    path('logout/',views.user_logout,name="logout"),
    # path('special/',views.special,name="special"),

    # path('password-reset/',auth_views.password_reset,name="password_reset"),
    # path("password-reset/done/",auth_views.password_reset_done,name="password_reset_done"),
    # path('password-reset/confirm/(?P<uidb64>[\w-]+)/(?P<token>[\w-]+)/',auth_views.password_reset_confirm,name="password_reset_confirm"),
    # path("password-reset/complete/",auth_views.password_reset_complete,name="password_reset_complete"),

    path('',include('django.contrib.auth.urls')),
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

templates/MasterLayout/baseLayout.html
<html>
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <style>
          img {
                  border-radius: 50%;
              }
          #right_bar{
            position:absolute;
            right:10px;
          }
          #my_nav_bar{
            position:relative;
            width:100%
          }
        </style>
        <title>Sports Room</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
    </head>
    {% load static %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <link rel="stylesheet" href="{% static '/css/style.css'%}">
    <link rel="stylesheet" href="{% static '/css/bootstrap.min.css'%}">
    <script src="{% static 'sportsEquipment/detail.js' %}"></script>
    <script src="{% static 'sportsEquipment/delete.js' %}"></script>
    <body>
        <nav class="navbar navbar-expand navbar-dark bg-dark" id="my_nav_bar">

          <img src="/media/profile_pics/IIIT-B_logo copy.jpg" style="max-height:50px"/>
          <a class="navbar-brand nav-link" href="{% url 'sportsEquipment:home' %}" style="font-size:14px">Sportsroom<br>IIITB</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample02" aria-controls="navbarsExample02" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarsExample02">

            {% if user.is_staff %}
              <ul class="navbar-nav " style="margin-right: 100px">
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'sportsEquipment:pendingRequest' %}">Pending Request <span class="sr-only">(current)</span></a>
              </li>

              <li class="nav-item active">
                <a class="nav-link" href="{% url 'sportsEquipment:approvedRequest' %}">Processed Request <span class="sr-only">(current)</span></a>
              </li>

              <li class="nav-item active">
                <a class="nav-link" href="{% url 'sportsEquipment:addEquip' %}">Add Equipment <span class="sr-only">(current)</span></a>
              </li>

              <li class="nav-item active">
                <a class="nav-link" href="{% url 'sportsEquipment:addGround' %}">Add Ground <span class="sr-only">(current)</span></a>
              </li>

              <li class="nav-item active">
                <a class="nav-link" href="{% url 'sportsEquipment:viewEquipList' %}">View Equipment <span class="sr-only">(current)</span></a>
              </li>
              <!--<li class="nav-item">-->
              <!--<li class="nav-item active">-->
                <!--<a class="nav-link" href="#">View requests <span class="sr-only">(current)</span></a>-->
              <!--</li>-->
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'sportsEquipment:penalty' %}">Check Penalty <span class="sr-only">(current)</span></a>
              </li>

            </ul>
            {% else %}
              <ul class="navbar-nav " style="margin-right: 100px" >
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'sportsEquipment:eqpRequest' %}">Request Equipment <span class="sr-only">(current)</span></a>
              </li>

              <li class="nav-item active">
                <a class="nav-link" href="{% url 'sportsEquipment:groundRequests' %}">Request Grounds <span class="sr-only">(current)</span></a>
              </li>

              <li class="nav-item active">
                <a class="nav-link" href="{% url 'sportsEquipment:viewRequest' %}">View Requests <span class="sr-only">(current)</span></a>
              </li>

              <li class="nav-item active">
                <a class="nav-link" href="{% url 'sportsEquipment:viewEquipList' %}">View Equipment <span class="sr-only">(current)</span></a>
              </li>

              <li class="nav-item active">
                <a class="nav-link" href="{% url 'sportsEquipment:viewGrounds' %}"> View Current Grounds & Holders <span class="sr-only">(current)</span></a>
              </li>

              {% block penalty %}

              {%  endblock%}

            </ul>
            {% endif %}

            <div id="right_bar">
              {% block rightbar %}

              {%  endblock%}
            </div>

             <!--  <div class ="profImg">
                    <img  src="/media/{{ userProfile.profile_pic }}" style="width:50px" alt="{{ user }}"/>
                    {% if user.is_authenticated %}
                    </div>
                    <div class="dropdown"> -->
                    <!-- <a class="nav-link" href="{% url 'login:logout' %}">Logout</a>
                      {% else %}
                    <a class="nav-link" href="{% url 'login:user_login' %}">Login</a>
                      {% endif %}
   -->

                    <!-- <button class="btn dropdown-toggle" type="button" data-toggle="dropdown" style="color: white"></button> -->
                   <!--  <ul class="dropdown-menu">
                    {% if user.is_authenticated %}
                      <li><a class="nav-link" href="{% url 'login:logout' %}">Logout</a></li>
                      <li><a class="nav-link" href="#">Hello, {{ user.username }}</a></li>
                    {% else %}
                      <li><a class="nav-link" href="{% url 'login:user_login' %}">Login</a></li>
                      <li><a class="nav-link" href="#">Hello, {{ user.username }}</a></li>
                    {% endif %}
                    </ul> -->
<!-- </div> -->


              </div>
          </div>
        </nav>

        <div class="container">

            {% block body %}

            {%  endblock%}

        </div>

    </body>

</html>

templates/MasterLayout/old_baseLayout.html
<html>

    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <style>
          img {
                  border-radius: 50%;  
              }
        </style>
        <title>Sports Room</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
    </head>
    {% load static %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <link rel="stylesheet" href="{% static '/css/style.css'%}">
    <link rel="stylesheet" href="{% static '/css/bootstrap.min.css'%}">
    <script src="{% static 'sportsEquipment/detail.js' %}"></script>
    <script src="{% static 'sportsEquipment/delete.js' %}"></script>
    <body>
        <nav class="navbar navbar-expand navbar-dark bg-dark">
          <img src="/media/profile_pics/IIIT-B_logo copy.jpg" style="max-height:50px"/>
          <a class="navbar-brand nav-link" href="{% url 'sportsEquipment:home' %}" style="font-size:14px">Sportsroom<br>IIITB</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample02" aria-controls="navbarsExample02" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarsExample02">

            {% if user.is_staff %}
              <ul class="navbar-nav " style="margin-right: 900px">
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'sportsEquipment:pendingRequest' %}">Pending Request <span class="sr-only">(current)</span></a>
              </li>

              <li class="nav-item active">
                <a class="nav-link" href="{% url 'sportsEquipment:approvedRequest' %}">Processed Request <span class="sr-only">(current)</span></a>
              </li>

              <li class="nav-item active">
                <a class="nav-link" href="{% url 'sportsEquipment:addEquip' %}">Add Equipment <span class="sr-only">(current)</span></a>
              </li>

              <li class="nav-item active">
                <a class="nav-link" href="{% url 'sportsEquipment:viewEquipList' %}">View Equipment <span class="sr-only">(current)</span></a>
              </li>
              <!--<li class="nav-item">-->
              <!--<li class="nav-item active">-->
                <!--<a class="nav-link" href="#">View requests <span class="sr-only">(current)</span></a>-->
              <!--</li>-->
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'sportsEquipment:penalty' %}">Check Penalty <span class="sr-only">(current)</span></a>
              </li>

            </ul>
            {% else %}
              <ul class="navbar-nav " style="margin-right: 1000px" >
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'sportsEquipment:eqpRequest' %}">Request Equipment <span class="sr-only">(current)</span></a>
              </li>
              <!--<li class="nav-item">-->
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'sportsEquipment:viewRequest' %}">View Requests <span class="sr-only">(current)</span></a>
              </li>
              {% block penalty %}

            {%  endblock%}
              
            </ul>
            {% endif %}

            {% block rightbar %}

            {%  endblock%}

             <!--  <div class ="profImg">     
                    <img  src="/media/{{ userProfile.profile_pic }}" style="width:50px" alt="{{ user }}"/>
                    {% if user.is_authenticated %}
                    </div> 
                    <div class="dropdown"> -->
                    <!-- <a class="nav-link" href="{% url 'login:logout' %}">Logout</a>
                      {% else %}
                    <a class="nav-link" href="{% url 'login:user_login' %}">Login</a>
                      {% endif %}
   -->
                    
                    <!-- <button class="btn dropdown-toggle" type="button" data-toggle="dropdown" style="color: white"></button> -->
                   <!--  <ul class="dropdown-menu">
                    {% if user.is_authenticated %}
                      <li><a class="nav-link" href="{% url 'login:logout' %}">Logout</a></li>
                      <li><a class="nav-link" href="#">Hello, {{ user.username }}</a></li>
                    {% else %}
                      <li><a class="nav-link" href="{% url 'login:user_login' %}">Login</a></li>
                      <li><a class="nav-link" href="#">Hello, {{ user.username }}</a></li>
                    {% endif %}
                    </ul> -->
<!-- </div> -->
            

              </div>
          </div>
        </nav>

        <div class="container">

            {% block body %}

            {%  endblock%}

        </div>

    </body>

</html>